DROP TABLE CLASSROOM_INCIDENCES;

CREATE TABLE CLASSROOM_INCIDENCES
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ACADEMIC_YEAR_ID VARCHAR(10) NOT NULL,
	DATE DATE NOT NULL,
	TEACHER_ID VARCHAR(15) NOT NULL,
	STUDENT_ID VARCHAR(15) NOT NULL,
	ARRIVAL_TIME TIME NOT NULL,
	SENDER_TEACHER_ID VARCHAR(15),
	SCHOOL_MGMT_ORDER_CAUSE BOOLEAN,
	USE_OF_MOBILE_CAUSE BOOLEAN,
	BREAK_MATERIAL_CAUSE BOOLEAN,
	LACK_OF_RESPECT_CAUSE BOOLEAN,
	GO_OUT_FROM_SCHOOL_CAUSE BOOLEAN,
	DISTURB_CAUSE BOOLEAN,
	BREACH_OF_ORDER_CAUSE BOOLEAN,
	TO_NOT_WORK_CAUSE BOOLEAN,
	SMOKE_CAUSE BOOLEAN,
	STRONG_BAD_BEHAVIOUR BOOLEAN,
	INTERRUPT_STUDENTS_STUDY BOOLEAN,
	OTHER_CAUSE BOOLEAN,

	CONSTRAINT CLASSROOM_INCIDENCES_PK PRIMARY KEY (ID),
	CONSTRAINT CLASSROOM_INCIDENCES_FK1 FOREIGN KEY (ACADEMIC_YEAR_ID) REFERENCES ACADEMIC_YEARS (ID),
	CONSTRAINT CLASSROOM_INCIDENCES_FK2 FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID),
	CONSTRAINT CLASSROOM_INCIDENCES_FK3 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
	CONSTRAINT CLASSROOM_INCIDENCES_FK4 FOREIGN KEY (SENDER_TEACHER_ID) REFERENCES TEACHERS (ID)
);


INSERT INTO ACADEMIC_YEARS (ID, DESCRIPTION) VALUES ('2018-2019', 'Año Académico 2018-2019');

UPDATE CONFIG SET VALUE='2018-2019' WHERE PARAM_ID='CurrentAcademicYear';